title: sopel-plugins list
description: A simple site to list user-submitted Sopel plugins. Concept/WIP phase.

repository: sopel-irc/sopel

github:
  is_project_page: false

collections:
  plugins:
    output: true
    permalink: /info/:name/

defaults:
  - scope:
      path: ""
      type: "plugins"
    values:
      layout: plugin
