title: sopel-module list
description: A simple site to list user-submitted Sopel modules. Concept/WIP phase.

repository: sopel-irc/sopel

github:
  is_project_page: false

collections:
  modules:
    output: true
    permalink: /info/:name/

defaults:
  - scope:
      path: ""
      type: "modules"
    values:
      layout: module
